### ISSUE TITLE
Could not get unknown property 'check' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by IonutNegru87** [Piasy/AndroidCodeQualityConfig#10]
I am unable to integrate this config into my project.
I get the following error:
```
Error:FAILURE: Build failed with an exception.

* Where:
Script '[myprojectpath]\code_quality_tools\quality.gradle' line: 12

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'check' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
I have added in root project's **build.gradle**:
```
subprojects {
    // Code quality checks
    apply from: "$rootProject.projectDir/code_quality_tools/quality.gradle"
    afterEvaluate {
        check.dependsOn 'checkstyle', 'findbugs', 'pmd', 'lint'
    }
    ...
}
```

I have commented `check.dependsOn 'checkstyle', 'findbugs', 'pmd', 'lint'` in quality.gradle.

**Comment by Piasy** [comment]
Could you please checkout the [octostars-app branch of AndroidTDDBootStrap](https://github.com/Piasy/AndroidTDDBootStrap/tree/octostars-app)? I've updated several commits of these configs, please make sure you integrate in the same way as AndroidTDDBootStrap does.

**Comment by IonutNegru87** [comment]
Thank you,

I've done something similar, but instead of checking for a java module I'm checking for android module:
`def isAndroid = plugins.hasPlugin('com.android.application')`

And I'm making the checks based on this variable.

**Comment by Piasy** [comment]
Glad to hear that :)

**Comment by IonutNegru87** [comment]
The variable should actually be:
`def isAndroid = plugins.hasPlugin('com.android.application') ||
        plugins.hasPlugin('com.android.library')`

Otherwise android library modules will fail.
