### ISSUE TITLE
Is it possible config quality.gradle in root project?

### ISSUE THREAD

**Issue by gengjiawen** [Piasy/AndroidCodeQualityConfig#3]
If we can implement this, we need not config every module for multi-module project.

**Comment by gengjiawen** [comment]
For now, I am trying 

``` gradle
subprojects {
    apply from: "$rootProject.projectDir/AndroidCodeQualityConfig/quality.gradle"
}
```

But I am getting this error

``` shell
Could not get unknown property 'check' for ':commonLibrary' of type org.gradle.api.Project.
```

**Comment by gengjiawen** [comment]
Okay, finally find a way.For anyone want to try, you can using this in your root build.gradle file:

``` gradle
subprojects {
    apply from: "$rootProject.projectDir/AndroidCodeQualityConfig/quality.gradle"

    afterEvaluate {
        check.dependsOn 'checkstyle', 'findbugs', 'pmd', 'lint'
   }
}
```

Notice: You should first remove `check.dependsOn 'checkstyle', 'findbugs', 'pmd', 'lint'` in quality.gradle.

**Comment by Piasy** [comment]
I'll try to apply this, thanks!

**Comment by gengjiawen** [comment]
We can add this to readme, to provide as a second approach.

**Comment by gengjiawen** [comment]
@Piasy Just heads up, I am excluding android lint.
And I have create a pr for some compatibility issue.

**Comment by gengjiawen** [comment]
If you needs lint in multi-module project , you need to wrap android closure in afterEvalate in `quality.gradle`.

**Comment by gengjiawen** [comment]
I create a pr(https://github.com/Piasy/AndroidCodeQualityConfig/pull/6) for android lint, please have a look.
