### ISSUE TITLE
Considering quality check for java module as well?

### ISSUE THREAD

**Issue by Luolc** [Piasy/AndroidCodeQualityConfig#7]
In some of my projects I have both Android and Java modules. But this repo, as what it is named, is only for Android module(Can not use Android Lint in Java module and the classes path is different). For the check is helpful for Java code as well, would you considering update the `quality.gradle` to let it be able for both Java and Android module?  :)

Currently I simply judge whether a project is Java or Android module by a statement `plugins.hasPlugin('java')` in `quality.gradle`. It runs well up to now.

**Comment by Piasy** [comment]
Sure, actually [there was a `quality-java.gradle`](https://github.com/Piasy/AndroidCodeQualityConfig/blob/9a81ce05b9c7122a11aa7394c6d0a4ec128e2dda/quality-java.gradle).

**Comment by Luolc** [comment]
So maybe it is a better choice to combine the two gradle file into one. :) For there are many duplicated codes and we'd better to follow DRY principle. And is there a good way to setup the config in root project if using divided file `quality.gradle` and `quality-java.gradle`?

**Comment by Piasy** [comment]
Sure, but I'm a little bit busy this week :( pr is welcome!
